import { Header } from "@/components/header"



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import './globals.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      
      <body className="bg-slate-200">
      <Header />
        {children}
      </body>
    </html>
  )
}
